modLoader="javafml"     
loaderVersion="[26,)"     

[[mods]]
modId="villagemanager"
version="${file.jarVersion}"     
displayName="Village Manager"

[[dependencies.examplemod]]     
    modId="forge"     
    mandatory=true     
    versionRange="[27,)"     
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"